name: CD - frontend DEPLOY Production

on:
  push:    
   branchs:
    - main
   paths: 
    - 'front-end/**'
      
jobs:
  frontend_deploy_prod:
    if: github.ref == 'refs/heads/main'
    name: Frontend Production CD 
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Deploy Prod CI front-end
        run: echo "Deployando para production..."
